src/rate/api/urls.py
from django.urls import path

from rate.api import views

app_name = 'api-rate'


urlpatterns = [
    path('latest-rates/', views.LatestRatesView.as_view(),
         name='latest-rates'),
    path('rates/', views.RateListCreateView.as_view(), name='rates'),
    path('rates/<int:pk>/', views.RateReadUpdateDeleteView.as_view(), name='rate'),
]

src/rate/urls.py
from django.urls import path

from rate import views

app_name = 'rate'

urlpatterns = [
    path('list/', views.RateList.as_view(), name='list'),
    path('edit/<int:pk>/', views.UpdateRate.as_view(), name='update'),
    path('delete/<int:pk>/', views.DeleteRate.as_view(), name='delete'),
    path('latest-rates/', views.LatestRatesView.as_view(), name='latest-rates'),
    path('download-csv/', views.RateDownloadCSV.as_view(), name='download-csv'),
    path('download-xlsx/', views.RateDownloadXLSX.as_view(), name='download-xlsx'),
]

src/settings/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, re_path
from django.views.generic import TemplateView

from drf_yasg import openapi
from drf_yasg.views import get_schema_view

from rest_framework import permissions

from rest_framework_simplejwt.views import TokenObtainPairView


schema_view = get_schema_view(
   openapi.Info(
      title="Snippets API",
      default_version='v1',
      description="Test description",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="contact@snippets.local"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
)

API_PREFIX = 'api/v1/'

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', TemplateView.as_view(template_name='index.html'), name='index'),

    path('account/', include('account.urls')),
    path('rate/', include('rate.urls')),

    # API
    path(f'{API_PREFIX}rate/', include('rate.api.urls')),
    path(f'{API_PREFIX}account/', include('account.api.urls')),
    path(f'{API_PREFIX}token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    re_path(rf'^{API_PREFIX}swagger(?P<format>\.json|\.yaml)$',
            schema_view.without_ui(cache_timeout=0), name='schema-json'),
    re_path(rf'^{API_PREFIX}swagger/$', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    re_path(rf'^{API_PREFIX}redoc/$', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]


if settings.DEBUG:
    import debug_toolbar

    urlpatterns.extend([
        path('__debug__/', include(debug_toolbar.urls)),
    ])

    urlpatterns.extend(static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

src/rate/models.py
from django.db import models

from rate import model_choices as mch
from rate.utils import to_decimal


class Rate(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    amount = models.DecimalField(max_digits=5, decimal_places=2)
    source = models.PositiveSmallIntegerField(choices=mch.SOURCE_CHOICES)  # get_{field}_display()
    currency_type = models.PositiveSmallIntegerField(choices=mch.CURRENCY_TYPE_CHOICES)
    type = models.PositiveSmallIntegerField(choices=mch.RATE_TYPE_CHOICES)  # noqa

    def save(self, *args, **kwargs):
        self.amount = to_decimal(self.amount)
        super().save(*args, **kwargs)


class Track(models.Model):
    counter = models.PositiveIntegerField(default=0)

src/rate/api/views.py
from rate.api.serializers import RateSerializer
from rate.models import Rate
from rate.selectors import get_latest_rates

from rest_framework import generics


class RateListCreateView(generics.ListCreateAPIView):
    # permission_classes = []
    # authentication_classes = []
    queryset = Rate.objects.all()
    serializer_class = RateSerializer


class RateReadUpdateDeleteView(generics.RetrieveUpdateDestroyAPIView):
    queryset = Rate.objects.all()
    serializer_class = RateSerializer


class LatestRatesView(generics.ListAPIView):
    permission_classes = []
    authentication_classes = []
    serializer_class = RateSerializer

    def get_queryset(self):
        return get_latest_rates()

    # def get(self, **kwargs):
    #     rates =
    #     return Response(RateSerializer(rates, many=True).data)

src/rate/views.py
import csv
from datetime import datetime

from django.contrib.auth.mixins import UserPassesTestMixin
from django.db.models import F
from django.http import HttpResponse
from django.urls import reverse_lazy
from django.views.generic import DeleteView, TemplateView, UpdateView, View

from django_filters.views import FilterView

from openpyxl import Workbook

from rate.filters import RateFilter
from rate.models import Rate, Track
from rate.selectors import get_latest_rates
from rate.utils import display


class RateList(FilterView):
    queryset = Rate.objects.all()
    template_name = 'rate/rate_list.html'
    paginate_by = 25
    filterset_class = RateFilter

    def get(self, request, *args, **kwargs):
        # print('GET')
        # track, created = Track.objects.get_or_create()
        # from time import sleep
        # print(track.counter)
        # sleep(30)
        # track.counter = track.counter + 1
        # track.save()
        Track.objects.all().update(counter=F('counter') + 1)

        return super().get(request, *args, **kwargs)

    # def get_context_data(self, *args, **kwargs):
    #     context = super().get_context_data(*args, **kwargs)
    #     get = dict(tuple(self.request.GET.items()))
    #     get.pop('page', None)
    #     context['request_GET'] = urlencode(get)
    #     return context


class LatestRatesView(TemplateView):
    template_name = 'latest-rates.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['object_list'] = get_latest_rates()
        return context


class RateDownloadCSV(View):
    HEADERS = (
        'id',
        'created',
        'source',
        'amount',
        'type',
    )
    queryset = Rate.objects.all().iterator()

    def get(self, request):
        # Create the HttpResponse object with the appropriate CSV header.
        response = self.get_response()

        writer = csv.writer(response)  # response.write
        writer.writerow(self.__class__.HEADERS)

        for rate in self.queryset:
            # row
            values = []
            for attr in self.__class__.HEADERS:
                values.append(display(rate, attr))

            writer.writerow(values)

        return response

    def get_response(self):
        response = HttpResponse(content_type='text/csv')
        response['Content-Disposition'] = 'attachment; filename="rate.csv"'
        return response


class RateDownloadXLSX(View):
    columns = [
        'id',
        'created',
        'source',
        'amount',
        'type',
    ]
    queryset = Rate.objects.all().iterator()

    def get(self, request):
        """
        Downloads all movies as Excel file with a single worksheet
        """
        # movie_queryset = Movie.objects.all()

        response = HttpResponse(
            content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
        )
        today = datetime.now().strftime("%Y-%m-%d")
        response['Content-Disposition'] = f'attachment; filename={today}-rates.xlsx'
        workbook = Workbook()

        # Get active worksheet/tab
        worksheet = workbook.active
        worksheet.title = 'Movies'

        # Define the titles for columns
        row_num = 1

        # Assign the titles for each cell of the header
        for col_num, column_title in enumerate(self.columns, 1):
            cell = worksheet.cell(row=row_num, column=col_num)
            cell.value = column_title

        # Iterate through all movies
        for rate in self.queryset:
            row_num += 1

            # row
            row = []
            for attr in self.__class__.columns:
                row.append(display(rate, attr))

            # Assign the data for each cell of the row
            for col_num, cell_value in enumerate(row, 1):
                cell = worksheet.cell(row=row_num, column=col_num)
                cell.value = cell_value

        workbook.save(response)

        return response


class UpdateRate(UserPassesTestMixin, UpdateView):
    template_name = 'rate-update.html'
    queryset = Rate.objects.all()
    fields = ('amount', 'source', 'currency_type', 'type')
    success_url = reverse_lazy('rate:list')

    def test_func(self):
        return self.request.user.is_authenticated and \
               self.request.user.is_superuser


class DeleteRate(UserPassesTestMixin, DeleteView):
    queryset = Rate.objects.all()
    success_url = reverse_lazy('rate:list')

    def get(self, request, *args, **kwargs):
        return super().delete(request, *args, **kwargs)

    def test_func(self):
        return self.request.user.is_authenticated and \
               self.request.user.is_superuser

src/rate/templates/rate/rate_list.html
{% extends 'base.html' %}

{% load paginator %}

{% block title %}Rate List{% endblock title %}

{% block content %}
    <a href="{% url 'rate:download-csv' %}">Download rates</a>
    <a href="{% url 'rate:download-xlsx' %}">Download rates (xlsx)</a>

    <form method="get">
        {{ filter.form.as_p }}
        <button type="submit" class="btn btn-primary">
            <span class="glyphicon glyphicon-search"></span> Search
        </button>
    </form>

    <table class="table table-striped">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">id</th>
            <th scope="col">created</th>
            <th scope="col">source</th>
            <th scope="col">amount</th>
            <th scope="col">type</th>

            {% if request.user.is_superuser %}
                <th scope="col">Update</th>
                <th scope="col">Delete</th>
            {% endif %}

        </tr>
        </thead>
        <tbody>
        {% for rate in object_list %}
            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td>{{ rate.id }}</td>
                <td>{{ rate.created }}</td>
                <td>{{ rate.get_source_display|title }}</td>
                <td>{{ rate.amount }}</td>
                <td>{{ rate.get_type_display|upper }}</td>

                {% if request.user.is_superuser %}
                    <td><a href="{% url 'rate:update' rate.pk %}">Update</a></td>
                    <td><a href="{% url 'rate:delete' rate.pk %}">Delete</a></td>
                {% endif %}

            </tr>
        {% endfor %}
        </tbody>
    </table>

    {% if is_paginated %}
        {% paginate page_obj %}
{#        <div class="pagination">#}
{#    <span class="step-links">#}
{#        {% if page_obj.has_previous %}#}
{#            <a href="?page=1&{{ request_GET }}">&laquo; first</a>#}
{#            <a href="?page={{ page_obj.previous_page_number }}&{{ request_GET }}">previous</a>#}
{#        {% endif %}#}
{##}
{#        <span class="current">#}
{#            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.#}
{#        </span>#}
{##}
{#        {% if page_obj.has_next %}#}
{#            <a href="?page={{ page_obj.next_page_number }}&{{ request_GET }}">next</a>#}
{#            <a href="?page={{ page_obj.paginator.num_pages }}&{{ request_GET }}">last &raquo;</a>#}
{#        {% endif %}#}
{#    </span>#}
{#        </div>#}
    {% endif %}
{% endblock content %}